cert: tls.crt
key: tls.key
inputs:
- type: KubernetesTokenReview
  name: kubernetes
  path: /kubernetes
  config:
    audience:
    - kubernetes
    issuers:
      domain:
        publicKey: key.pub
        idPrefix: spiffe://domain/path
        subjectPrefix: spiffe://domain/path
        groupPrefix: spiffe://domain/path
    claims:
      id: sub
      subject: sub
      groups: groups
outputs:
- type: KubernetesTokenReview
  name: kubernetes
  path: /kubernetes
  config:
    audience: kubernetes
    maxTTL: 300
